### ISSUE TITLE
Embed error.

### ISSUE THREAD

**Issue by LeRegedit** [hoemotion/mass-dm-discord#1]
When I enable Embed I get the following error:

UnboundLocalError: local variable 'embed' referenced before assignment

**Comment by hoemotion** [comment]
> When I enable Embed I get the following error:
> 
> 
> 
> UnboundLocalError: local variable 'embed' referenced before assignment

Hmm this should't happen
You can join the support server so i can help you maybe a it cuz github issues suck

**Comment by hoemotion** [comment]
Issue was fixed
