### ISSUE TITLE
How do I not get banned?

### ISSUE THREAD

**Issue by WISH12345** [hoemotion/mass-dm-discord#3]
![image](https://user-images.githubusercontent.com/79537154/145072987-8477bbd9-39f5-44e3-9ef8-24ee29b01538.png)

**Comment by hoemotion** [comment]
its **not** bypassable but some tokens have a better quality than the others (which means they dont get banned fast), join the support server for more infos!
Also check out [this](https://github.com/hoemotion/Discord-Mass-DM) new mass dm repo 🚀
